/*
 * Test data strategy for jml.javax.safetycritical.Services.
 *
 * Generated by JMLUnitNG 1.3 (103), 2013-05-13 00:16 +0200.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

 
package jml.javax.safetycritical.Services_JML_Data;

import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;

/**
 * Test data strategy for jml.javax.safetycritical.Services. Provides
 * test values for parameter "int ceiling" 
 * of method "void setCeiling(Object, int)". 
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2013-05-13 00:16 +0200
 */
public class setCeiling__Object_target__int_ceiling__10__ceiling
  extends ClassStrategy_int {
  /**
   * @return local-scope values for parameter 
   *  "int ceiling".
   */
  public RepeatedAccessIterator<?> localValues() {
  	return new ObjectArrayIterator<Object>
  	(new Object[]
  	 { /* add local-scope int values or generators here */ });
  }
}
