/*
 * Test data strategy for jml.javax.safetycritical.StorageParameters.
 *
 * Generated by JMLUnitNG 1.3 (103), 2013-05-11 06:02 +0200.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

 
package jml.javax.safetycritical.StorageParameters_JML_Data;

import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;

/**
 * Test data strategy for jml.javax.safetycritical.StorageParameters. Provides
 * test values for parameter "long totalBackingStore" 
 * of method "StorageParameters(long, long[])". 
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2013-05-11 06:02 +0200
 */
public class StorageParameters__long_totalBackingStore__long1DArray_sizes__0__totalBackingStore
  extends ClassStrategy_long {
  /**
   * @return local-scope values for parameter 
   *  "long totalBackingStore".
   */
  public RepeatedAccessIterator<?> localValues() {
  	return new ObjectArrayIterator<Object>
  	(new Object[]
  	 { /* add local-scope long values or generators here */ 
  	    10L, -10L
  	 });
  }
}
