/*
 * Test data strategy for jml.javax.safetycritical.PriorityScheduler.
 *
 * Generated by JMLUnitNG 1.3 (103), 2013-05-12 19:04 +0200.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

 
package jml.javax.safetycritical.PriorityScheduler_JML_Data;

import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;

/**
 * Test data strategy for jml.javax.safetycritical.PriorityScheduler. Provides
 * test values for parameter "int[] stack" 
 * of method "void add(ManagedEventHandler, int[])". 
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2013-05-12 19:04 +0200
 */
public class add__ManagedEventHandler_handler__int1DArray_stack__25__stack
  extends ClassStrategy_int1DArray {
  /**
   * @return local-scope values for parameter 
   *  "int[] stack".
   */
  public RepeatedAccessIterator<?> localValues() {
  	return new ObjectArrayIterator<Object>
  	(new Object[]
  	 { /* add local-scope int[] values or generators here */ });
  }

  /**
   * Constructor.
   * The maximum length of generated arrays can be controlled here for
   * parameter "int[] stack" of method "void add(ManagedEventHandler, int[])"
   * by changing the parameter to <code>setMaxLength</code>.
   * In addition, the data generators used can be changed by adding 
   * additional data class lines, or by removing some of the automatically 
   * generated ones. Since this is the lowest level of strategy, the 
   * behavior will be exactly as you specify here if you clear the existing 
   * list of classes first.
   *
   * @see NonPrimitiveStrategy#addDataClass(Class<?>)
   * @see NonPrimitiveStrategy#clearDataClasses()
   * @see ArrayStrategy#setMaxLength(int)
   */
  public add__ManagedEventHandler_handler__int1DArray_stack__25__stack() {
    super();
    // uncomment to control the maximum array length, 1 by default
    // setMaxLength(1); 
    // uncomment to control the maximum reflective instantiation
    // recursion depth, 0 by default
    // setMaxRecursionDepth(0);
  }
}
