/*
 * Test data strategy for jml.javax.safetycritical.AbsoluteTime.
 *
 * Generated by JMLUnitNG 1.3 (103), 2013-05-15 01:01 +0200.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

package jml.javax.safetycritical.AbsoluteTime_JML_Data;


import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;
import jml.javax.safetycritical.PackageStrategy_long;
/**
 * Test data strategy for jml.javax.safetycritical.AbsoluteTime. Provides
 * class-scope test values for type long.
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2013-05-15 01:01 +0200
 */
public class ClassStrategy_long 
  extends PackageStrategy_long {
  /**
   * @return class-scope values for type long.
   */
  public RepeatedAccessIterator<?> classValues() {
    return new ObjectArrayIterator<Object>
    (new Object[] 
  	 { /* add class-scope long values or generators here */ });
  }
  
  /**
   * defaultValues() from AbsoluteTime; overridden by HSO
   * @return default values for type long.
   */
  public RepeatedAccessIterator<?> defaultValues() {
    return new ObjectArrayIterator<Object>
    (new Object[] 
     { /* add default HighResolutionTime values or generators here */ 
        1L
     });
  }
}
