/*
 * Test data strategy for jml.javax.safetycritical.PrivateMemory.
 *
 * Generated by JMLUnitNG 1.3 (103), 2013-05-12 03:18 +0200.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

 
package jml.javax.safetycritical.PrivateMemory_JML_Data;

import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;

/**
 * Test data strategy for jml.javax.safetycritical.PrivateMemory. Provides
 * test values for parameter "int size" 
 * of method "PrivateMemory(int)". 
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2013-05-12 03:18 +0200
 */
public class PrivateMemory__int_size__0__size
  extends ClassStrategy_int {
  /**
   * @return local-scope values for parameter 
   *  "int size".
   */
  public RepeatedAccessIterator<?> localValues() {
  	return new ObjectArrayIterator<Object>
  	(new Object[]
  	 { /* add local-scope int values or generators here */ });
  }
}
