/*
 * Test data strategy for jml.javax.safetycritical.CyclicSchedule.
 *
 * Generated by JMLUnitNG 1.3 (103), 2013-05-12 20:10 +0200.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

 
package jml.javax.safetycritical.CyclicSchedule_JML_Data;

import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;

/**
 * Test data strategy for jml.javax.safetycritical.CyclicSchedule. Provides
 * test values for parameter "Frame[] frames" 
 * of method "CyclicSchedule(Frame[])". 
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2013-05-12 20:10 +0200
 */
public class CyclicSchedule__Frame1DArray_frames__25__frames
  extends ClassStrategy_jml_javax_safetycritical_Frame1DArray {
  /**
   * @return local-scope values for parameter 
   *  "Frame[] frames".
   */
  public RepeatedAccessIterator<?> localValues() {
  	return new ObjectArrayIterator<Object>
  	(new Object[]
  	 { /* add local-scope jml.javax.safetycritical.Frame[] values or generators here */ });
  }

  /**
   * Constructor.
   * The maximum length of generated arrays can be controlled here for
   * parameter "Frame[] frames" of method "CyclicSchedule(Frame[])"
   * by changing the parameter to <code>setMaxLength</code>.
   * In addition, the data generators used can be changed by adding 
   * additional data class lines, or by removing some of the automatically 
   * generated ones. Since this is the lowest level of strategy, the 
   * behavior will be exactly as you specify here if you clear the existing 
   * list of classes first.
   *
   * @see NonPrimitiveStrategy#addDataClass(Class<?>)
   * @see NonPrimitiveStrategy#clearDataClasses()
   * @see ArrayStrategy#setMaxLength(int)
   */
  public CyclicSchedule__Frame1DArray_frames__25__frames() {
    super();
    // uncomment to control the maximum array length, 1 by default
    // setMaxLength(1); 
    // uncomment to control the maximum reflective instantiation
    // recursion depth, 0 by default
    // setMaxRecursionDepth(0);
  }
}
