/*
 * Test data strategy for jml.vm.Memory.
 *
 * Generated by JMLUnitNG 1.3 (103), 2013-04-06 17:35 +0200.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

package jml.vm;

import java.util.LinkedList;
import java.util.List;

import org.jmlspecs.jmlunitng.iterator.InstantiationIterator;
import org.jmlspecs.jmlunitng.iterator.IteratorAdapter;
import org.jmlspecs.jmlunitng.iterator.NonNullMultiIterator;
import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;
import org.jmlspecs.jmlunitng.strategy.ObjectStrategy;

/**
 * Test data strategy for jml.vm.Memory. Provides
 * instances of jml.vm.Memory for testing, using
 * parameters from constructor tests.
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2013-04-06 17:35 +0200
 */
public class Memory_InstanceStrategy extends ObjectStrategy {
  /**
   * @return local-scope instances of Memory.
   */
  public RepeatedAccessIterator<?> localValues() {
    return new ObjectArrayIterator<Object>
    (new Object[]
     { /* add jml.vm.Memory values or generators here */ });
  }

  /**
   * @return default instances of Memory, generated
   *  using constructor test parameters.
   */ 
  public RepeatedAccessIterator<jml.vm.Memory> defaultValues() {
    final List<RepeatedAccessIterator<jml.vm.Memory>> iters = 
      new LinkedList<RepeatedAccessIterator<jml.vm.Memory>>();

    // an instantiation iterator for the default constructor
    // (if there isn't one, it will fail silently)
    iters.add(new InstantiationIterator<jml.vm.Memory>
      (jml.vm.Memory.class, 
       new Class<?>[0], 
       new ObjectArrayIterator<Object[]>(new Object[][]{{}})));

    // parameters for method Memory(int, int)
    iters.add(new InstantiationIterator<jml.vm.Memory>
      (jml.vm.Memory.class, 
       new Class<?>[]
       {int.class, 
        int.class},
       Memory_JML_Test.p_Memory__int_base__int_size__0().wrapped()));

    return new NonNullMultiIterator<jml.vm.Memory>(iters);
  }

  /**
   * Constructor. The boolean parameter to <code>setReflective</code>
   * determines whether or not reflection will be used to generate
   * test objects, and the int parameter to <code>setMaxRecursionDepth</code>
   * determines how many levels reflective generation of self-referential classes
   * will recurse.
   *
   * @see ObjectStrategy#setReflective(boolean)
   * @see ObjectStrategy#setMaxRecursionDepth(int)
   */
  public Memory_InstanceStrategy() {
    super(jml.vm.Memory.class);
    setReflective(false);
    // uncomment to control the maximum reflective instantiation
    // recursion depth, 0 by default
    // setMaxRecursionDepth(0);
  }
}
