/*
 * Test data strategy for package jml.vm.
 *
 * Generated by JMLUnitNG 1.3 (103), 2013-04-06 17:35 +0200.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

 package jml.vm;

import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;
import org.jmlspecs.jmlunitng.strategy.IntStrategy;

/**
 * Test data strategy for package jml.vm. Provides
 * package-scope test values for type int.
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2013-04-06 17:35 +0200
 */
public class PackageStrategy_int 
  extends IntStrategy {
  /**
   * @return package-scope values for type int.
   */
  public RepeatedAccessIterator<?> packageValues() {
    return new ObjectArrayIterator<Object>
    (new Object[] 
     { /* add package-scope int values or generators here */ });
  }
  
  /**
   * defaultValues() from IntStrategy; overridden by HSO
   * @return default values for type int.
   */
  public RepeatedAccessIterator<?> defaultValues() {
    return new ObjectArrayIterator<Object>
    (new Object[] 
     { /* add default long values or generators here */ 
       1, 100
     });
  }
}
