/*
 * Test data strategy for jml.vm.RealtimeClock.
 *
 * Generated by JMLUnitNG 1.3 (103), 2013-06-17 06:17 +0200.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

package jml.vm;

import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;
import org.jmlspecs.jmlunitng.strategy.ObjectStrategy;

/**
 * Test data strategy for jml.vm.RealtimeClock. Provides
 * instances of jml.vm.RealtimeClock for testing, using
 * parameters from constructor tests.
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2013-06-17 06:17 +0200
 */
public class RealtimeClock_InstanceStrategy extends ObjectStrategy {
  /**
   * @return local-scope instances of RealtimeClock.
   */
  public RepeatedAccessIterator<?> localValues() {
    return new ObjectArrayIterator<Object>
    (new Object[]
     { /* add jml.vm.RealtimeClock values or generators here */ });
  }

  /**
   * @return default instances of RealtimeClock, generated
   *  using constructor test parameters.
   */ 
  public RepeatedAccessIterator<jml.vm.RealtimeClock> defaultValues() {
    // abstract classes cannot be constructed
    return new ObjectArrayIterator<jml.vm.RealtimeClock>(new jml.vm.RealtimeClock[0]);
  }

  /**
   * Constructor. The boolean parameter to <code>setReflective</code>
   * determines whether or not reflection will be used to generate
   * test objects, and the int parameter to <code>setMaxRecursionDepth</code>
   * determines how many levels reflective generation of self-referential classes
   * will recurse.
   *
   * @see ObjectStrategy#setReflective(boolean)
   * @see ObjectStrategy#setMaxRecursionDepth(int)
   */
  public RealtimeClock_InstanceStrategy() {
    super(jml.vm.RealtimeClock.class);
    setReflective(false);
    // uncomment to control the maximum reflective instantiation
    // recursion depth, 0 by default
    // setMaxRecursionDepth(0);
  }
}
