/*
 * Test data strategy for jml.javax.safetycritical.AbsoluteTime.
 *
 * Generated by JMLUnitNG 1.3 (103), 2013-05-15 01:01 +0200.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

package jml.javax.safetycritical;

import java.util.LinkedList;
import java.util.List;

import org.jmlspecs.jmlunitng.iterator.InstantiationIterator;
import org.jmlspecs.jmlunitng.iterator.IteratorAdapter;
import org.jmlspecs.jmlunitng.iterator.NonNullMultiIterator;
import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;
import org.jmlspecs.jmlunitng.strategy.ObjectStrategy;

/**
 * Test data strategy for jml.javax.safetycritical.AbsoluteTime. Provides
 * instances of jml.javax.safetycritical.AbsoluteTime for testing, using
 * parameters from constructor tests.
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2013-05-15 01:01 +0200
 */
public class AbsoluteTime_InstanceStrategy extends ObjectStrategy {
  /**
   * @return local-scope instances of AbsoluteTime.
   */
  public RepeatedAccessIterator<?> localValues() {
    return new ObjectArrayIterator<Object>
    (new Object[]
     { /* add jml.javax.safetycritical.AbsoluteTime values or generators here */ });
  }

  /**
   * @return default instances of AbsoluteTime, generated
   *  using constructor test parameters.
   */ 
  public RepeatedAccessIterator<jml.javax.safetycritical.AbsoluteTime> defaultValues() {
    final List<RepeatedAccessIterator<jml.javax.safetycritical.AbsoluteTime>> iters = 
      new LinkedList<RepeatedAccessIterator<jml.javax.safetycritical.AbsoluteTime>>();

    // an instantiation iterator for the default constructor
    // (if there isn't one, it will fail silently)
    iters.add(new InstantiationIterator<jml.javax.safetycritical.AbsoluteTime>
      (jml.javax.safetycritical.AbsoluteTime.class, 
       new Class<?>[0], 
       new ObjectArrayIterator<Object[]>(new Object[][]{{}})));

    // parameters for method AbsoluteTime(long, int)
    iters.add(new InstantiationIterator<jml.javax.safetycritical.AbsoluteTime>
      (jml.javax.safetycritical.AbsoluteTime.class, 
       new Class<?>[]
       {long.class, 
        int.class},
       AbsoluteTime_JML_Test.p_AbsoluteTime__long_millis__int_nanos__0().wrapped()));

    // parameters for method AbsoluteTime(long, int, Clock)
    iters.add(new InstantiationIterator<jml.javax.safetycritical.AbsoluteTime>
      (jml.javax.safetycritical.AbsoluteTime.class, 
       new Class<?>[]
       {long.class, 
        int.class, 
        jml.javax.safetycritical.Clock.class},
       AbsoluteTime_JML_Test.p_AbsoluteTime__long_millis__int_nanos__Clock_clock__25().wrapped()));

    // parameters for method AbsoluteTime(Clock)
    iters.add(new InstantiationIterator<jml.javax.safetycritical.AbsoluteTime>
      (jml.javax.safetycritical.AbsoluteTime.class, 
       new Class<?>[]
       {jml.javax.safetycritical.Clock.class},
       AbsoluteTime_JML_Test.p_AbsoluteTime__Clock_clock__25().wrapped()));

    // parameters for method AbsoluteTime(AbsoluteTime)
    iters.add(new InstantiationIterator<jml.javax.safetycritical.AbsoluteTime>
      (jml.javax.safetycritical.AbsoluteTime.class, 
       new Class<?>[]
       {jml.javax.safetycritical.AbsoluteTime.class},
       AbsoluteTime_JML_Test.p_AbsoluteTime__AbsoluteTime_time__25().wrapped()));

    return new NonNullMultiIterator<jml.javax.safetycritical.AbsoluteTime>(iters);
  }

  /**
   * Constructor. The boolean parameter to <code>setReflective</code>
   * determines whether or not reflection will be used to generate
   * test objects, and the int parameter to <code>setMaxRecursionDepth</code>
   * determines how many levels reflective generation of self-referential classes
   * will recurse.
   *
   * @see ObjectStrategy#setReflective(boolean)
   * @see ObjectStrategy#setMaxRecursionDepth(int)
   */
  public AbsoluteTime_InstanceStrategy() {
    super(jml.javax.safetycritical.AbsoluteTime.class);
    setReflective(false);
    // uncomment to control the maximum reflective instantiation
    // recursion depth, 0 by default
    // setMaxRecursionDepth(0);
  }
}
