/*
 * Test data strategy for jml.javax.safetycritical.Frame.
 *
 * Generated by JMLUnitNG 1.3 (103), 2013-05-12 19:51 +0200.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

package jml.javax.safetycritical;

import java.util.LinkedList;
import java.util.List;

import org.jmlspecs.jmlunitng.iterator.InstantiationIterator;
import org.jmlspecs.jmlunitng.iterator.IteratorAdapter;
import org.jmlspecs.jmlunitng.iterator.NonNullMultiIterator;
import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;
import org.jmlspecs.jmlunitng.strategy.ObjectStrategy;

/**
 * Test data strategy for jml.javax.safetycritical.Frame. Provides
 * instances of jml.javax.safetycritical.Frame for testing, using
 * parameters from constructor tests.
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2013-05-12 19:51 +0200
 */
public class Frame_InstanceStrategy extends ObjectStrategy {
  /**
   * @return local-scope instances of Frame.
   */
  public RepeatedAccessIterator<?> localValues() {
    return new ObjectArrayIterator<Object>
    (new Object[]
     { /* add jml.javax.safetycritical.Frame values or generators here */ });
  }

  /**
   * @return default instances of Frame, generated
   *  using constructor test parameters.
   */ 
  public RepeatedAccessIterator<jml.javax.safetycritical.Frame> defaultValues() {
    final List<RepeatedAccessIterator<jml.javax.safetycritical.Frame>> iters = 
      new LinkedList<RepeatedAccessIterator<jml.javax.safetycritical.Frame>>();

    // an instantiation iterator for the default constructor
    // (if there isn't one, it will fail silently)
    iters.add(new InstantiationIterator<jml.javax.safetycritical.Frame>
      (jml.javax.safetycritical.Frame.class, 
       new Class<?>[0], 
       new ObjectArrayIterator<Object[]>(new Object[][]{{}})));

    // parameters for method Frame(RelativeTime, PeriodicEventHandler[])
    iters.add(new InstantiationIterator<jml.javax.safetycritical.Frame>
      (jml.javax.safetycritical.Frame.class, 
       new Class<?>[]
       {jml.javax.safetycritical.RelativeTime.class, 
        jml.javax.safetycritical.PeriodicEventHandler[].class},
       Frame_JML_Test.p_Frame__RelativeTime_duration__PeriodicEventHandler1DArray_handlers__50().wrapped()));

    return new NonNullMultiIterator<jml.javax.safetycritical.Frame>(iters);
  }

  /**
   * Constructor. The boolean parameter to <code>setReflective</code>
   * determines whether or not reflection will be used to generate
   * test objects, and the int parameter to <code>setMaxRecursionDepth</code>
   * determines how many levels reflective generation of self-referential classes
   * will recurse.
   *
   * @see ObjectStrategy#setReflective(boolean)
   * @see ObjectStrategy#setMaxRecursionDepth(int)
   */
  public Frame_InstanceStrategy() {
    super(jml.javax.safetycritical.Frame.class);
    setReflective(false);
    // uncomment to control the maximum reflective instantiation
    // recursion depth, 0 by default
    // setMaxRecursionDepth(0);
  }
}
