/*
 * Test data strategy for jml.javax.safetycritical.ImmortalMemory.
 *
 * Generated by JMLUnitNG 1.3 (103), 2013-06-16 14:02 +0200.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

package jml.javax.safetycritical;

import java.util.LinkedList;
import java.util.List;

import org.jmlspecs.jmlunitng.iterator.InstantiationIterator;
import org.jmlspecs.jmlunitng.iterator.IteratorAdapter;
import org.jmlspecs.jmlunitng.iterator.NonNullMultiIterator;
import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;
import org.jmlspecs.jmlunitng.strategy.ObjectStrategy;

/**
 * Test data strategy for jml.javax.safetycritical.ImmortalMemory. Provides
 * instances of jml.javax.safetycritical.ImmortalMemory for testing, using
 * parameters from constructor tests.
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2013-06-16 14:02 +0200
 */
public class ImmortalMemory_InstanceStrategy extends ObjectStrategy {
  /**
   * @return local-scope instances of ImmortalMemory.
   */
  public RepeatedAccessIterator<?> localValues() {
    return new ObjectArrayIterator<Object>
    (new Object[]
     { /* add jml.javax.safetycritical.ImmortalMemory values or generators here */ });
  }

  /**
   * @return default instances of ImmortalMemory, generated
   *  using constructor test parameters.
   */ 
  public RepeatedAccessIterator<jml.javax.safetycritical.ImmortalMemory> defaultValues() {
    final List<RepeatedAccessIterator<jml.javax.safetycritical.ImmortalMemory>> iters = 
      new LinkedList<RepeatedAccessIterator<jml.javax.safetycritical.ImmortalMemory>>();

    // an instantiation iterator for the default constructor
    // (if there isn't one, it will fail silently)
    iters.add(new InstantiationIterator<jml.javax.safetycritical.ImmortalMemory>
      (jml.javax.safetycritical.ImmortalMemory.class, 
       new Class<?>[0], 
       new ObjectArrayIterator<Object[]>(new Object[][]{{}})));

    // parameters for method ImmortalMemory(int)
    iters.add(new InstantiationIterator<jml.javax.safetycritical.ImmortalMemory>
      (jml.javax.safetycritical.ImmortalMemory.class, 
       new Class<?>[]
       {int.class},
       ImmortalMemory_JML_Test.p_ImmortalMemory__int_sizeOfArea__0().wrapped()));

    return new NonNullMultiIterator<jml.javax.safetycritical.ImmortalMemory>(iters);
  }

  /**
   * Constructor. The boolean parameter to <code>setReflective</code>
   * determines whether or not reflection will be used to generate
   * test objects, and the int parameter to <code>setMaxRecursionDepth</code>
   * determines how many levels reflective generation of self-referential classes
   * will recurse.
   *
   * @see ObjectStrategy#setReflective(boolean)
   * @see ObjectStrategy#setMaxRecursionDepth(int)
   */
  public ImmortalMemory_InstanceStrategy() {
    super(jml.javax.safetycritical.ImmortalMemory.class);
    setReflective(false);
    // uncomment to control the maximum reflective instantiation
    // recursion depth, 0 by default
    // setMaxRecursionDepth(0);
  }
}
