/*
 * Test Oracle Class for jml.javax.safetycritical.MissionMemory
 * For Use With JML4 RAC
 *
 * Generated by JMLUnitNG 1.3 (103), 2013-06-16 14:48 +0200.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

package jml.javax.safetycritical;


import java.io.PrintWriter;
import java.util.ArrayList;

import org.jmlspecs.jmlunitng.iterator.IteratorWrapper;
import org.jmlspecs.jmlunitng.iterator.ParameterArrayIterator;
import org.jmlspecs.jmlunitng.testng.BasicTestListener;
import org.jmlspecs.jmlunitng.testng.PreconditionSkipException;
import org.testng.Assert;
import org.testng.TestException;
import org.testng.TestNG;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;
import org.testng.xml.XmlSuite;

import org.jmlspecs.jml4.rac.runtime.JMLAssertionError;
import org.jmlspecs.jml4.rac.runtime.JMLChecker;
import org.jmlspecs.jml4.rac.runtime.JMLEntryPreconditionError;
import org.jmlspecs.jml4.rac.runtime.JMLEvaluationError;

import jml.javax.safetycritical.MissionMemory_JML_Data.*;


/**
 * Test oracles generated by JMLUnitNG for JML4 RAC of class
 * jml.javax.safetycritical.MissionMemory.
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2013-06-16 14:48 +0200
 */

public class MissionMemory_JML_Test {
  /**
   * The main method. Allows the tests to be run without a testng.xml or
   * the use of the TestNG executable/plugin.
   *
   * @param the_args Command line arguments, ignored.
   */
  public static void main(String[] the_args) {
    final TestNG testng_runner = new TestNG();
    final Class<?>[] classes = {MissionMemory_JML_Test.class};
    final BasicTestListener listener =
      new BasicTestListener(new PrintWriter(System.out));
    testng_runner.setUseDefaultListeners(false);
    testng_runner.setXmlSuites(new ArrayList<XmlSuite>());
    testng_runner.setTestClasses(classes);
    testng_runner.addListener(listener);
    testng_runner.run();
  }

  /** 
   * A test to ensure that RAC is enabled before running other tests.
   */
  @Test
  public void test_racEnabled() {
    Assert.assertTrue
    (JMLChecker.isRACCompiled(jml.javax.safetycritical.MissionMemory.class),
     "JMLUnitNG tests can only run on RAC-compiled code.");
  } 

  /**
   * A test for a constructor.
   *
   * @param size The int to be passed.
   */
  @Test(dependsOnMethods = { "test_racEnabled" }, 
        dataProvider = "p_MissionMemory__int_size__0")
  public void test_MissionMemory__int_size__0
  (final int size) {
    try {
      new jml.javax.safetycritical.MissionMemory(size);
    }
    catch (final JMLEntryPreconditionError $e) {
      // meaningless test
      throw new PreconditionSkipException($e.getMessage());
    }
    catch (final JMLEvaluationError $e) {
      if ($e.getCause() instanceof JMLEntryPreconditionError) {
        // meaningless test
        throw new PreconditionSkipException($e.getCause().getMessage());
      } else {
        // failed test
        throw new TestException($e.getCause().getMessage());
      }
    }
    catch (final JMLAssertionError $e) {
      // test failure
      throw new TestException($e.getMessage());
    }
    catch (final Throwable $e) {
      // test failure for some reason other than assertion violation
      throw new TestException($e.getMessage());
    }
  }

  /**
   * A test for method getHandlerPortal.
   *
   * @param the_test_object The MissionMemory to call the test method on.
   */
  @Test(dependsOnMethods = { "test_racEnabled" }, 
        dataProvider = "p_instance_only")
  public void test_getHandlerPortal__0
  (final jml.javax.safetycritical.MissionMemory the_test_object ) {
      if (the_test_object == null) {
        throw new PreconditionSkipException
        ("could not construct an object to test");
      }
    try {
      the_test_object.getHandlerPortal();
    }
    catch (final JMLEntryPreconditionError $e) {
      // meaningless test
      throw new PreconditionSkipException($e.getMessage());
    }
    catch (final JMLEvaluationError $e) {
      if ($e.getCause() instanceof JMLEntryPreconditionError) {
        // meaningless test
        throw new PreconditionSkipException($e.getCause().getMessage());
      } else {
        // failed test
        throw new TestException($e.getCause().getMessage());
      }
    }
    catch (final JMLAssertionError $e) {
      // test failure
      throw new TestException($e.getMessage());
    }
    catch (final Throwable $e) {
      // test failure for some reason other than assertion violation
      throw new TestException($e.getMessage());
    }
  }

  /**
   * A test for method setHandlerPortal.
   *
   * @param the_test_object The MissionMemory to call the test method on.
   * @param handlerSet The HandlerSet to be passed.
   */
  @Test(dependsOnMethods = { "test_racEnabled" }, 
        dataProvider = "p_setHandlerPortal__HandlerSet_handlerSet__25")
  public void test_setHandlerPortal__HandlerSet_handlerSet__25
  (final jml.javax.safetycritical.MissionMemory the_test_object, 
   final jml.javax.safetycritical.HandlerSet handlerSet) {
      if (the_test_object == null) {
        throw new PreconditionSkipException
        ("could not construct an object to test");
      }
    try {
      the_test_object.setHandlerPortal(handlerSet);
    }
    catch (final JMLEntryPreconditionError $e) {
      // meaningless test
      throw new PreconditionSkipException($e.getMessage());
    }
    catch (final JMLEvaluationError $e) {
      if ($e.getCause() instanceof JMLEntryPreconditionError) {
        // meaningless test
        throw new PreconditionSkipException($e.getCause().getMessage());
      } else {
        // failed test
        throw new TestException($e.getCause().getMessage());
      }
    }
    catch (final JMLAssertionError $e) {
      // test failure
      throw new TestException($e.getMessage());
    }
    catch (final Throwable $e) {
      // test failure for some reason other than assertion violation
      throw new TestException($e.getMessage());
    }
  }

  /**
   * A test for method enterToInitialize.
   *
   * @param the_test_object The MissionMemory to call the test method on.
   * @param mission The Mission to be passed.
   */
  @Test(dependsOnMethods = { "test_racEnabled" }, 
        dataProvider = "p_enterToInitialize__Mission_mission__25")
  public void test_enterToInitialize__Mission_mission__25
  (final jml.javax.safetycritical.MissionMemory the_test_object, 
   final jml.javax.safetycritical.Mission mission) {
      if (the_test_object == null) {
        throw new PreconditionSkipException
        ("could not construct an object to test");
      }
    try {
      the_test_object.enterToInitialize(mission);
    }
    catch (final JMLEntryPreconditionError $e) {
      // meaningless test
      throw new PreconditionSkipException($e.getMessage());
    }
    catch (final JMLEvaluationError $e) {
      if ($e.getCause() instanceof JMLEntryPreconditionError) {
        // meaningless test
        throw new PreconditionSkipException($e.getCause().getMessage());
      } else {
        // failed test
        throw new TestException($e.getCause().getMessage());
      }
    }
    catch (final JMLAssertionError $e) {
      // test failure
      throw new TestException($e.getMessage());
    }
    catch (final Throwable $e) {
      // test failure for some reason other than assertion violation
      throw new TestException($e.getMessage());
    }
  }

  /**
   * A test for method enterToExecute.
   *
   * @param the_test_object The MissionMemory to call the test method on.
   * @param mission The Mission to be passed.
   */
  @Test(dependsOnMethods = { "test_racEnabled" }, 
        dataProvider = "p_enterToExecute__Mission_mission__25")
  public void test_enterToExecute__Mission_mission__25
  (final jml.javax.safetycritical.MissionMemory the_test_object, 
   final jml.javax.safetycritical.Mission mission) {
      if (the_test_object == null) {
        throw new PreconditionSkipException
        ("could not construct an object to test");
      }
    try {
      the_test_object.enterToExecute(mission);
    }
    catch (final JMLEntryPreconditionError $e) {
      // meaningless test
      throw new PreconditionSkipException($e.getMessage());
    }
    catch (final JMLEvaluationError $e) {
      if ($e.getCause() instanceof JMLEntryPreconditionError) {
        // meaningless test
        throw new PreconditionSkipException($e.getCause().getMessage());
      } else {
        // failed test
        throw new TestException($e.getCause().getMessage());
      }
    }
    catch (final JMLAssertionError $e) {
      // test failure
      throw new TestException($e.getMessage());
    }
    catch (final Throwable $e) {
      // test failure for some reason other than assertion violation
      throw new TestException($e.getMessage());
    }
  }

  /**
   * A test for method enterToCleanup.
   *
   * @param the_test_object The MissionMemory to call the test method on.
   * @param mission The Mission to be passed.
   */
  @Test(dependsOnMethods = { "test_racEnabled" }, 
        dataProvider = "p_enterToCleanup__Mission_mission__25")
  public void test_enterToCleanup__Mission_mission__25
  (final jml.javax.safetycritical.MissionMemory the_test_object, 
   final jml.javax.safetycritical.Mission mission) {
      if (the_test_object == null) {
        throw new PreconditionSkipException
        ("could not construct an object to test");
      }
    try {
      the_test_object.enterToCleanup(mission);
    }
    catch (final JMLEntryPreconditionError $e) {
      // meaningless test
      throw new PreconditionSkipException($e.getMessage());
    }
    catch (final JMLEvaluationError $e) {
      if ($e.getCause() instanceof JMLEntryPreconditionError) {
        // meaningless test
        throw new PreconditionSkipException($e.getCause().getMessage());
      } else {
        // failed test
        throw new TestException($e.getCause().getMessage());
      }
    }
    catch (final JMLAssertionError $e) {
      // test failure
      throw new TestException($e.getMessage());
    }
    catch (final Throwable $e) {
      // test failure for some reason other than assertion violation
      throw new TestException($e.getMessage());
    }
  }

  /**
   * Data provider for constructor MissionMemory(int).
   * @return An iterator over strategies to use for parameter generation.
   */
  @SuppressWarnings({"unchecked"})
  @DataProvider(name = "p_MissionMemory__int_size__0", 
                parallel = false)
  public static IteratorWrapper<Object[]> p_MissionMemory__int_size__0() {
    return new IteratorWrapper<Object[]>
    (new ParameterArrayIterator
         (MissionMemory__int_size__0__size.class));
  }



  /**
   * Data provider for method void setHandlerPortal(HandlerSet).
   * @return An iterator over strategies to use for parameter generation.
   */
  @SuppressWarnings({"unchecked"})
  @DataProvider(name = "p_setHandlerPortal__HandlerSet_handlerSet__25", 
                parallel = false)
  public static IteratorWrapper<Object[]> p_setHandlerPortal__HandlerSet_handlerSet__25() {
    return new IteratorWrapper<Object[]>
    (new ParameterArrayIterator
         (MissionMemory_InstanceStrategy.class,
          setHandlerPortal__HandlerSet_handlerSet__25__handlerSet.class));
  }


  /**
   * Data provider for method void enterToInitialize(Mission).
   * @return An iterator over strategies to use for parameter generation.
   */
  @SuppressWarnings({"unchecked"})
  @DataProvider(name = "p_enterToInitialize__Mission_mission__25", 
                parallel = false)
  public static IteratorWrapper<Object[]> p_enterToInitialize__Mission_mission__25() {
    return new IteratorWrapper<Object[]>
    (new ParameterArrayIterator
         (MissionMemory_InstanceStrategy.class,
          enterToInitialize__Mission_mission__25__mission.class));
  }


  /**
   * Data provider for method void enterToExecute(Mission).
   * @return An iterator over strategies to use for parameter generation.
   */
  @SuppressWarnings({"unchecked"})
  @DataProvider(name = "p_enterToExecute__Mission_mission__25", 
                parallel = false)
  public static IteratorWrapper<Object[]> p_enterToExecute__Mission_mission__25() {
    return new IteratorWrapper<Object[]>
    (new ParameterArrayIterator
         (MissionMemory_InstanceStrategy.class,
          enterToExecute__Mission_mission__25__mission.class));
  }


  /**
   * Data provider for method void enterToCleanup(Mission).
   * @return An iterator over strategies to use for parameter generation.
   */
  @SuppressWarnings({"unchecked"})
  @DataProvider(name = "p_enterToCleanup__Mission_mission__25", 
                parallel = false)
  public static IteratorWrapper<Object[]> p_enterToCleanup__Mission_mission__25() {
    return new IteratorWrapper<Object[]>
    (new ParameterArrayIterator
         (MissionMemory_InstanceStrategy.class,
          enterToCleanup__Mission_mission__25__mission.class));
  }


  /**
   * Data provider for methods with no parameters.
   * @return An iterator over the main class strategy.
   */
  @SuppressWarnings({"unchecked"})
  @DataProvider(name = "p_instance_only", 
                parallel = false)
  public static IteratorWrapper<Object[]> p_instance_only() {
    return new IteratorWrapper<Object[]>
    (new ParameterArrayIterator(MissionMemory_InstanceStrategy.class));
  }
}