/*
 * Test data strategy for package jml.javax.safetycritical.
 *
 * Generated by JMLUnitNG 1.3 (103), 2013-04-06 05:29 +0200.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

 package jml.javax.safetycritical;

import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;
import org.jmlspecs.jmlunitng.strategy.LongStrategy;

/**
 * Test data strategy for package jml.javax.safetycritical. Provides
 * package-scope test values for type long.
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2013-04-06 05:29 +0200
 */
public class PackageStrategy_long 
  extends LongStrategy {
  /**
   * @return package-scope values for type long.
   */
  public RepeatedAccessIterator<?> packageValues() {
    return new ObjectArrayIterator<Object>
    (new Object[] 
     { /* add package-scope long values or generators here */ 
     });
  }
  
  /**
   * defaultValues() from LongStrategy; overridden by HSO
   * @return default values for type long.
   */
  public RepeatedAccessIterator<?> defaultValues() {
    return new ObjectArrayIterator<Object>
    (new Object[] 
     { /* add default long values or generators here */ 
       3L
     });
  }
}
