/*
 * Test Oracle Class for jml.javax.safetycritical.PeriodicParameters
 * For Use With JML4 RAC
 *
 * Generated by JMLUnitNG 1.3 (103), 2013-06-17 00:11 +0200.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

package jml.javax.safetycritical;


import java.io.PrintWriter;
import java.util.ArrayList;

import org.jmlspecs.jmlunitng.iterator.IteratorWrapper;
import org.jmlspecs.jmlunitng.iterator.ParameterArrayIterator;
import org.jmlspecs.jmlunitng.testng.BasicTestListener;
import org.jmlspecs.jmlunitng.testng.PreconditionSkipException;
import org.testng.Assert;
import org.testng.TestException;
import org.testng.TestNG;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;
import org.testng.xml.XmlSuite;

import org.jmlspecs.jml4.rac.runtime.JMLAssertionError;
import org.jmlspecs.jml4.rac.runtime.JMLChecker;
import org.jmlspecs.jml4.rac.runtime.JMLEntryPreconditionError;
import org.jmlspecs.jml4.rac.runtime.JMLEvaluationError;

import jml.javax.safetycritical.PeriodicParameters_JML_Data.*;


/**
 * Test oracles generated by JMLUnitNG for JML4 RAC of class
 * jml.javax.safetycritical.PeriodicParameters.
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2013-06-17 00:11 +0200
 */

public class PeriodicParameters_JML_Test {
  /**
   * The main method. Allows the tests to be run without a testng.xml or
   * the use of the TestNG executable/plugin.
   *
   * @param the_args Command line arguments, ignored.
   */
  public static void main(String[] the_args) {
    final TestNG testng_runner = new TestNG();
    final Class<?>[] classes = {PeriodicParameters_JML_Test.class};
    final BasicTestListener listener =
      new BasicTestListener(new PrintWriter(System.out));
    testng_runner.setUseDefaultListeners(false);
    testng_runner.setXmlSuites(new ArrayList<XmlSuite>());
    testng_runner.setTestClasses(classes);
    testng_runner.addListener(listener);
    testng_runner.run();
  }

  /** 
   * A test to ensure that RAC is enabled before running other tests.
   */
  @Test
  public void test_racEnabled() {
    Assert.assertTrue
    (JMLChecker.isRACCompiled(jml.javax.safetycritical.PeriodicParameters.class),
     "JMLUnitNG tests can only run on RAC-compiled code.");
  } 

  /**
   * A test for method getPeriod.
   *
   * @param the_test_object The PeriodicParameters to call the test method on.
   */
  @Test(dependsOnMethods = { "test_racEnabled" }, 
        dataProvider = "p_instance_only")
  public void test_getPeriod__0
  (final jml.javax.safetycritical.PeriodicParameters the_test_object ) {
      if (the_test_object == null) {
        throw new PreconditionSkipException
        ("could not construct an object to test");
      }
    try {
      the_test_object.getPeriod();
    }
    catch (final JMLEntryPreconditionError $e) {
      // meaningless test
      throw new PreconditionSkipException($e.getMessage());
    }
    catch (final JMLEvaluationError $e) {
      if ($e.getCause() instanceof JMLEntryPreconditionError) {
        // meaningless test
        throw new PreconditionSkipException($e.getCause().getMessage());
      } else {
        // failed test
        throw new TestException($e.getCause().getMessage());
      }
    }
    catch (final JMLAssertionError $e) {
      // test failure
      throw new TestException($e.getMessage());
    }
    catch (final Throwable $e) {
      // test failure for some reason other than assertion violation
      throw new TestException($e.getMessage());
    }
  }

  /**
   * A test for a constructor.
   *
   * @param start The RelativeTime to be passed.
   * @param period The RelativeTime to be passed.
   */
  @Test(dependsOnMethods = { "test_racEnabled" }, 
        dataProvider = "p_PeriodicParameters__RelativeTime_start__RelativeTime_period__50")
  public void test_PeriodicParameters__RelativeTime_start__RelativeTime_period__50
  (final jml.javax.safetycritical.RelativeTime start, final jml.javax.safetycritical.RelativeTime period) {
    try {
      new jml.javax.safetycritical.PeriodicParameters(start, period);
    }
    catch (final JMLEntryPreconditionError $e) {
      // meaningless test
      throw new PreconditionSkipException($e.getMessage());
    }
    catch (final JMLEvaluationError $e) {
      if ($e.getCause() instanceof JMLEntryPreconditionError) {
        // meaningless test
        throw new PreconditionSkipException($e.getCause().getMessage());
      } else {
        // failed test
        throw new TestException($e.getCause().getMessage());
      }
    }
    catch (final JMLAssertionError $e) {
      // test failure
      throw new TestException($e.getMessage());
    }
    catch (final Throwable $e) {
      // test failure for some reason other than assertion violation
      throw new TestException($e.getMessage());
    }
  }

  /**
   * A test for a constructor.
   *
   * @param start The RelativeTime to be passed.
   * @param period The RelativeTime to be passed.
   * @param deadline The RelativeTime to be passed.
   * @param missHandler The AperiodicEventHandler to be passed.
   */
  @Test(dependsOnMethods = { "test_racEnabled" }, 
        dataProvider = "p_PeriodicParameters__RelativeTime_start__RelativeTime_period__RelativeTime_deadline__AperiodicEventHandler_missHandler__100")
  public void test_PeriodicParameters__RelativeTime_start__RelativeTime_period__RelativeTime_deadline__AperiodicEventHandler_missHandler__100
  (final jml.javax.safetycritical.RelativeTime start, final jml.javax.safetycritical.RelativeTime period, final jml.javax.safetycritical.RelativeTime deadline, final jml.javax.safetycritical.AperiodicEventHandler missHandler) {
    try {
      new jml.javax.safetycritical.PeriodicParameters(start, period, deadline, missHandler);
    }
    catch (final JMLEntryPreconditionError $e) {
      // meaningless test
      throw new PreconditionSkipException($e.getMessage());
    }
    catch (final JMLEvaluationError $e) {
      if ($e.getCause() instanceof JMLEntryPreconditionError) {
        // meaningless test
        throw new PreconditionSkipException($e.getCause().getMessage());
      } else {
        // failed test
        throw new TestException($e.getCause().getMessage());
      }
    }
    catch (final JMLAssertionError $e) {
      // test failure
      throw new TestException($e.getMessage());
    }
    catch (final Throwable $e) {
      // test failure for some reason other than assertion violation
      throw new TestException($e.getMessage());
    }
  }

  /**
   * A test for method getStart.
   *
   * @param the_test_object The PeriodicParameters to call the test method on.
   */
  @Test(dependsOnMethods = { "test_racEnabled" }, 
        dataProvider = "p_instance_only")
  public void test_getStart__0
  (final jml.javax.safetycritical.PeriodicParameters the_test_object ) {
      if (the_test_object == null) {
        throw new PreconditionSkipException
        ("could not construct an object to test");
      }
    try {
      the_test_object.getStart();
    }
    catch (final JMLEntryPreconditionError $e) {
      // meaningless test
      throw new PreconditionSkipException($e.getMessage());
    }
    catch (final JMLEvaluationError $e) {
      if ($e.getCause() instanceof JMLEntryPreconditionError) {
        // meaningless test
        throw new PreconditionSkipException($e.getCause().getMessage());
      } else {
        // failed test
        throw new TestException($e.getCause().getMessage());
      }
    }
    catch (final JMLAssertionError $e) {
      // test failure
      throw new TestException($e.getMessage());
    }
    catch (final Throwable $e) {
      // test failure for some reason other than assertion violation
      throw new TestException($e.getMessage());
    }
  }

  /**
   * Data provider for constructor PeriodicParameters(RelativeTime, RelativeTime).
   * @return An iterator over strategies to use for parameter generation.
   */
  @SuppressWarnings({"unchecked"})
  @DataProvider(name = "p_PeriodicParameters__RelativeTime_start__RelativeTime_period__50", 
                parallel = false)
  public static IteratorWrapper<Object[]> p_PeriodicParameters__RelativeTime_start__RelativeTime_period__50() {
    return new IteratorWrapper<Object[]>
    (new ParameterArrayIterator
         (PeriodicParameters__RelativeTime_start__RelativeTime_period__50__start.class,
          PeriodicParameters__RelativeTime_start__RelativeTime_period__50__period.class));
  }


  /**
   * Data provider for constructor PeriodicParameters(RelativeTime, RelativeTime, RelativeTime, AperiodicEventHandler).
   * @return An iterator over strategies to use for parameter generation.
   */
  @SuppressWarnings({"unchecked"})
  @DataProvider(name = "p_PeriodicParameters__RelativeTime_start__RelativeTime_period__RelativeTime_deadline__AperiodicEventHandler_missHandler__100", 
                parallel = false)
  public static IteratorWrapper<Object[]> p_PeriodicParameters__RelativeTime_start__RelativeTime_period__RelativeTime_deadline__AperiodicEventHandler_missHandler__100() {
    return new IteratorWrapper<Object[]>
    (new ParameterArrayIterator
         (PeriodicParameters__RelativeTime_start__RelativeTime_period__RelativeTime_deadline__AperiodicEventHandler_missHandler__100__start.class,
          PeriodicParameters__RelativeTime_start__RelativeTime_period__RelativeTime_deadline__AperiodicEventHandler_missHandler__100__period.class,
          PeriodicParameters__RelativeTime_start__RelativeTime_period__RelativeTime_deadline__AperiodicEventHandler_missHandler__100__deadline.class,
          PeriodicParameters__RelativeTime_start__RelativeTime_period__RelativeTime_deadline__AperiodicEventHandler_missHandler__100__missHandler.class));
  }



  /**
   * Data provider for methods with no parameters.
   * @return An iterator over the main class strategy.
   */
  @SuppressWarnings({"unchecked"})
  @DataProvider(name = "p_instance_only", 
                parallel = false)
  public static IteratorWrapper<Object[]> p_instance_only() {
    return new IteratorWrapper<Object[]>
    (new ParameterArrayIterator(PeriodicParameters_InstanceStrategy.class));
  }
}