/*
 * Test data strategy for jml.javax.safetycritical.PeriodicParameters.
 *
 * Generated by JMLUnitNG 1.3 (103), 2013-04-08 08:42 +0200.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

package jml.javax.safetycritical;

import java.util.LinkedList;
import java.util.List;

import org.jmlspecs.jmlunitng.iterator.InstantiationIterator;
import org.jmlspecs.jmlunitng.iterator.IteratorAdapter;
import org.jmlspecs.jmlunitng.iterator.NonNullMultiIterator;
import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;
import org.jmlspecs.jmlunitng.strategy.ObjectStrategy;

/**
 * Test data strategy for jml.javax.safetycritical.PeriodicParameters. Provides
 * instances of jml.javax.safetycritical.PeriodicParameters for testing, using
 * parameters from constructor tests.
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2013-04-08 08:42 +0200
 */
public class PeriodicParameters_InstanceStrategy extends ObjectStrategy {
  /**
   * @return local-scope instances of PeriodicParameters.
   */
  public RepeatedAccessIterator<?> localValues() {
    return new ObjectArrayIterator<Object>
    (new Object[]
     { /* add jml.javax.safetycritical.PeriodicParameters values or generators here */ });
  }

  /**
   * @return default instances of PeriodicParameters, generated
   *  using constructor test parameters.
   */ 
  public RepeatedAccessIterator<jml.javax.safetycritical.PeriodicParameters> defaultValues() {
    final List<RepeatedAccessIterator<jml.javax.safetycritical.PeriodicParameters>> iters = 
      new LinkedList<RepeatedAccessIterator<jml.javax.safetycritical.PeriodicParameters>>();

    // an instantiation iterator for the default constructor
    // (if there isn't one, it will fail silently)
    iters.add(new InstantiationIterator<jml.javax.safetycritical.PeriodicParameters>
      (jml.javax.safetycritical.PeriodicParameters.class, 
       new Class<?>[0], 
       new ObjectArrayIterator<Object[]>(new Object[][]{{}})));

    // parameters for method PeriodicParameters(RelativeTime, RelativeTime)
    iters.add(new InstantiationIterator<jml.javax.safetycritical.PeriodicParameters>
      (jml.javax.safetycritical.PeriodicParameters.class, 
       new Class<?>[]
       {jml.javax.safetycritical.RelativeTime.class, 
        jml.javax.safetycritical.RelativeTime.class},
       PeriodicParameters_JML_Test.p_PeriodicParameters__RelativeTime_start__RelativeTime_period__50().wrapped()));

    // parameters for method PeriodicParameters(RelativeTime, RelativeTime, RelativeTime, AperiodicEventHandler)
    iters.add(new InstantiationIterator<jml.javax.safetycritical.PeriodicParameters>
      (jml.javax.safetycritical.PeriodicParameters.class, 
       new Class<?>[]
       {jml.javax.safetycritical.RelativeTime.class, 
        jml.javax.safetycritical.RelativeTime.class, 
        jml.javax.safetycritical.RelativeTime.class, 
        jml.javax.safetycritical.AperiodicEventHandler.class},
       PeriodicParameters_JML_Test.p_PeriodicParameters__RelativeTime_start__RelativeTime_period__RelativeTime_deadline__AperiodicEventHandler_missHandler__100().wrapped()));

    return new NonNullMultiIterator<jml.javax.safetycritical.PeriodicParameters>(iters);
  }

  /**
   * Constructor. The boolean parameter to <code>setReflective</code>
   * determines whether or not reflection will be used to generate
   * test objects, and the int parameter to <code>setMaxRecursionDepth</code>
   * determines how many levels reflective generation of self-referential classes
   * will recurse.
   *
   * @see ObjectStrategy#setReflective(boolean)
   * @see ObjectStrategy#setMaxRecursionDepth(int)
   */
  public PeriodicParameters_InstanceStrategy() {
    super(jml.javax.safetycritical.PeriodicParameters.class);
    setReflective(false);
    // uncomment to control the maximum reflective instantiation
    // recursion depth, 0 by default
    // setMaxRecursionDepth(0);
  }
}
