/*
 * Test data strategy for jml.javax.safetycritical.StorageParameters.
 *
 * Generated by JMLUnitNG 1.3 (103), 2013-05-11 06:02 +0200.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

package jml.javax.safetycritical;

import java.util.LinkedList;
import java.util.List;

import org.jmlspecs.jmlunitng.iterator.InstantiationIterator;
import org.jmlspecs.jmlunitng.iterator.IteratorAdapter;
import org.jmlspecs.jmlunitng.iterator.NonNullMultiIterator;
import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;
import org.jmlspecs.jmlunitng.strategy.ObjectStrategy;

/**
 * Test data strategy for jml.javax.safetycritical.StorageParameters. Provides
 * instances of jml.javax.safetycritical.StorageParameters for testing, using
 * parameters from constructor tests.
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2013-05-11 06:02 +0200
 */
public class StorageParameters_InstanceStrategy extends ObjectStrategy {
  /**
   * @return local-scope instances of StorageParameters.
   */
  public RepeatedAccessIterator<?> localValues() {
    return new ObjectArrayIterator<Object>
    (new Object[]
     { /* add jml.javax.safetycritical.StorageParameters values or generators here */ });
  }

  /**
   * @return default instances of StorageParameters, generated
   *  using constructor test parameters.
   */ 
  public RepeatedAccessIterator<jml.javax.safetycritical.StorageParameters> defaultValues() {
    final List<RepeatedAccessIterator<jml.javax.safetycritical.StorageParameters>> iters = 
      new LinkedList<RepeatedAccessIterator<jml.javax.safetycritical.StorageParameters>>();

    // an instantiation iterator for the default constructor
    // (if there isn't one, it will fail silently)
    iters.add(new InstantiationIterator<jml.javax.safetycritical.StorageParameters>
      (jml.javax.safetycritical.StorageParameters.class, 
       new Class<?>[0], 
       new ObjectArrayIterator<Object[]>(new Object[][]{{}})));

    // parameters for method StorageParameters(long, long[])
    iters.add(new InstantiationIterator<jml.javax.safetycritical.StorageParameters>
      (jml.javax.safetycritical.StorageParameters.class, 
       new Class<?>[]
       {long.class, 
        long[].class},
       StorageParameters_JML_Test.p_StorageParameters__long_totalBackingStore__long1DArray_sizes__0().wrapped()));

    return new NonNullMultiIterator<jml.javax.safetycritical.StorageParameters>(iters);
  }

  /**
   * Constructor. The boolean parameter to <code>setReflective</code>
   * determines whether or not reflection will be used to generate
   * test objects, and the int parameter to <code>setMaxRecursionDepth</code>
   * determines how many levels reflective generation of self-referential classes
   * will recurse.
   *
   * @see ObjectStrategy#setReflective(boolean)
   * @see ObjectStrategy#setMaxRecursionDepth(int)
   */
  public StorageParameters_InstanceStrategy() {
    super(jml.javax.safetycritical.StorageParameters.class);
    setReflective(false);
    // uncomment to control the maximum reflective instantiation
    // recursion depth, 0 by default
    // setMaxRecursionDepth(0);
  }
}
