/*
 * Test data strategy for jml.javax.safetycritical.RelativeTime.
 *
 * Generated by JMLUnitNG 1.3 (103), 2013-04-07 23:37 +0200.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

 
package jml.javax.safetycritical.RelativeTime_JML_Data;

import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;

/**
 * Test data strategy for jml.javax.safetycritical.RelativeTime. Provides
 * test values for parameter "int nanos" 
 * of method "jml.javax.safetycritical.RelativeTime add(long, int, RelativeTime)". 
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2013-04-07 23:37 +0200
 */
public class add__long_millis__int_nanos__RelativeTime_dest__25__nanos
  extends ClassStrategy_int {
  /**
   * @return local-scope values for parameter 
   *  "int nanos".
   */
  public RepeatedAccessIterator<?> localValues() {
  	return new ObjectArrayIterator<Object>
  	(new Object[]
  	 { /* add local-scope int values or generators here */ 
  	    2
  	 });
  }
}
