/*
 * Test data strategy for jml.javax.safetycritical.RelativeTime.
 *
 * Generated by JMLUnitNG 1.3 (103), 2013-04-07 23:37 +0200.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

package jml.javax.safetycritical.RelativeTime_JML_Data;


import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;
import jml.javax.safetycritical.PackageStrategy_long;
/**
 * Test data strategy for jml.javax.safetycritical.RelativeTime. Provides
 * class-scope test values for type long.
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2013-04-07 23:37 +0200
 */
public class ClassStrategy_long 
  extends PackageStrategy_long {
  /**
   * @return class-scope values for type long.
   */
  public RepeatedAccessIterator<?> classValues() {
    return new ObjectArrayIterator<Object>
    (new Object[] 
  	 { /* add class-scope long values or generators here */ });
  }
}
