/*
 * Test data strategy for jml.javax.safetycritical.RelativeTime.
 *
 * Generated by JMLUnitNG 1.3 (103), 2013-04-07 23:37 +0200.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

 
package jml.javax.safetycritical.RelativeTime_JML_Data;

import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;

/**
 * Test data strategy for jml.javax.safetycritical.RelativeTime. Provides
 * test values for parameter "long millis" 
 * of method "RelativeTime(long, int)". 
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2013-04-07 23:37 +0200
 */
public class RelativeTime__long_millis__int_nanos__0__millis
  extends ClassStrategy_long {
  /**
   * @return local-scope values for parameter 
   *  "long millis".
   */
  public RepeatedAccessIterator<?> localValues() {
  	return new ObjectArrayIterator<Object>
  	(new Object[]
  	 { /* add local-scope long values or generators here */ 
  	    1L
  	 });
  }
}
