/*
 * Test data strategy for jml.javax.safetycritical.RelativeTime.
 *
 * Generated by JMLUnitNG 1.3 (103), 2013-04-07 23:37 +0200.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

 
package jml.javax.safetycritical.RelativeTime_JML_Data;

import jml.javax.safetycritical.Clock;
import jml.javax.safetycritical.RelativeTime;

import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;

/**
 * Test data strategy for jml.javax.safetycritical.RelativeTime. Provides
 * test values for parameter "RelativeTime dest" 
 * of method "jml.javax.safetycritical.RelativeTime subtract(RelativeTime, RelativeTime)". 
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2013-04-07 23:37 +0200
 */
public class subtract__RelativeTime_time__RelativeTime_dest__50__dest
  extends ClassStrategy_jml_javax_safetycritical_RelativeTime {
  /**
   * @return local-scope values for parameter 
   *  "RelativeTime dest".
   */
  public RepeatedAccessIterator<?> localValues() {
  	return new ObjectArrayIterator<Object>
  	(new Object[]
  	 { /* add local-scope jml.javax.safetycritical.RelativeTime values or generators here */ 
  	    new RelativeTime (0L, 0, Clock.getRealtimeClock())
  	 });
  }

  /**
   * Constructor.
   * The use of reflection can be controlled here for  
   * "RelativeTime dest" of method "jml.javax.safetycritical.RelativeTime subtract(RelativeTime, RelativeTime)" 
   * by changing the parameters to <code>setReflective</code>
   * and <code>setMaxRecursionDepth<code>.
   * In addition, the data generators used can be changed by adding 
   * additional data class lines, or by removing some of the automatically 
   * generated ones. Since this is the lowest level of strategy, the 
   * behavior will be exactly as you specify here if you clear the existing 
   * list of classes first.
   *
   * @see NonPrimitiveStrategy#addDataClass(Class<?>)
   * @see NonPrimitiveStrategy#clearDataClasses()
   * @see ObjectStrategy#setReflective(boolean)
   * @see ObjectStrategy#setMaxRecursionDepth(int)
   */
  public subtract__RelativeTime_time__RelativeTime_dest__50__dest() {
    super();
    // uncomment to control the maximum reflective instantiation
    // recursion depth, 0 by default
    // setMaxRecursionDepth(0);
  }
}
