/*
 * Test data strategy for jml.vm.Memory.
 *
 * Generated by JMLUnitNG 1.3 (103), 2013-04-06 17:35 +0200.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

package jml.vm.Memory_JML_Data;


import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;
import jml.vm.PackageStrategy_int;
/**
 * Test data strategy for jml.vm.Memory. Provides
 * class-scope test values for type int.
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2013-04-06 17:35 +0200
 */
public class ClassStrategy_int 
  extends PackageStrategy_int {
  /**
   * @return class-scope values for type int.
   */
  public RepeatedAccessIterator<?> classValues() {
    return new ObjectArrayIterator<Object>
    (new Object[] 
  	 { /* add class-scope int values or generators here */ });
  }
}
