/*
 * Test data strategy for jml.vm.Memory.
 *
 * Generated by JMLUnitNG 1.3 (103), 2013-04-06 17:35 +0200.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

 
package jml.vm.Memory_JML_Data;

import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;

/**
 * Test data strategy for jml.vm.Memory. Provides
 * test values for parameter "int size" 
 * of method "Memory(int, int)". 
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2013-04-06 17:35 +0200
 */
public class Memory__int_base__int_size__0__size
  extends ClassStrategy_int {
  /**
   * @return local-scope values for parameter 
   *  "int size".
   */
  public RepeatedAccessIterator<?> localValues() {
  	return new ObjectArrayIterator<Object>
  	(new Object[]
  	 { /* add local-scope int values or generators here */ });
  }
}
