/*
 * Test data strategy for jml.vm.Memory.
 *
 * Generated by JMLUnitNG 1.3 (103), 2013-04-06 17:35 +0200.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

 
package jml.vm.Memory_JML_Data;

import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;

/**
 * Test data strategy for jml.vm.Memory. Provides
 * test values for parameter "Memory newScope" 
 * of method "void switchToArea(Memory)". 
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2013-04-06 17:35 +0200
 */
public class switchToArea__Memory_newScope__7__newScope
  extends ClassStrategy_jml_vm_Memory {
  /**
   * @return local-scope values for parameter 
   *  "Memory newScope".
   */
  public RepeatedAccessIterator<?> localValues() {
  	return new ObjectArrayIterator<Object>
  	(new Object[]
  	 { /* add local-scope jml.vm.Memory values or generators here */ });
  }

  /**
   * Constructor.
   * The use of reflection can be controlled here for  
   * "Memory newScope" of method "void switchToArea(Memory)" 
   * by changing the parameters to <code>setReflective</code>
   * and <code>setMaxRecursionDepth<code>.
   * In addition, the data generators used can be changed by adding 
   * additional data class lines, or by removing some of the automatically 
   * generated ones. Since this is the lowest level of strategy, the 
   * behavior will be exactly as you specify here if you clear the existing 
   * list of classes first.
   *
   * @see NonPrimitiveStrategy#addDataClass(Class<?>)
   * @see NonPrimitiveStrategy#clearDataClasses()
   * @see ObjectStrategy#setReflective(boolean)
   * @see ObjectStrategy#setMaxRecursionDepth(int)
   */
  public switchToArea__Memory_newScope__7__newScope() {
    super();
    // uncomment to control the maximum reflective instantiation
    // recursion depth, 0 by default
    // setMaxRecursionDepth(0);
  }
}
