/*
 * Test data strategy for jml.javax.safetycritical.ImmortalMemory.
 *
 * Generated by JMLUnitNG 1.3 (103), 2013-06-16 14:02 +0200.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

 
package jml.javax.safetycritical.ImmortalMemory_JML_Data;

import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;

/**
 * Test data strategy for jml.javax.safetycritical.ImmortalMemory. Provides
 * test values for parameter "int sizeOfArea" 
 * of method "ImmortalMemory(int)". 
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2013-06-16 14:02 +0200
 */
public class ImmortalMemory__int_sizeOfArea__0__sizeOfArea
  extends ClassStrategy_int {
  /**
   * @return local-scope values for parameter 
   *  "int sizeOfArea".
   */
  public RepeatedAccessIterator<?> localValues() {
  	return new ObjectArrayIterator<Object>
  	(new Object[]
  	 { /* add local-scope int values or generators here */ 
  	   1000
  	 });
  }
}
