/*
 * Test data strategy for jml.javax.safetycritical.ManagedMemory.
 *
 * Generated by JMLUnitNG 1.3 (103), 2013-05-12 02:28 +0200.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

 
package jml.javax.safetycritical.ManagedMemory_JML_Data;

import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;

/**
 * Test data strategy for jml.javax.safetycritical.ManagedMemory. Provides
 * test values for parameter "Runnable logic" 
 * of method "void executeInAreaOf(Object, Runnable)". 
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2013-05-12 02:28 +0200
 */
public class executeInAreaOf__Object_obj__Runnable_logic__20__logic
  extends ClassStrategy_java_lang_Runnable {
  /**
   * @return local-scope values for parameter 
   *  "Runnable logic".
   */
  public RepeatedAccessIterator<?> localValues() {
  	return new ObjectArrayIterator<Object>
  	(new Object[]
  	 { /* add local-scope java.lang.Runnable values or generators here */ });
  }

  /**
   * Constructor.
   * The use of reflection can be controlled here for  
   * "Runnable logic" of method "void executeInAreaOf(Object, Runnable)" 
   * by changing the parameters to <code>setReflective</code>
   * and <code>setMaxRecursionDepth<code>.
   * In addition, the data generators used can be changed by adding 
   * additional data class lines, or by removing some of the automatically 
   * generated ones. Since this is the lowest level of strategy, the 
   * behavior will be exactly as you specify here if you clear the existing 
   * list of classes first.
   *
   * @see NonPrimitiveStrategy#addDataClass(Class<?>)
   * @see NonPrimitiveStrategy#clearDataClasses()
   * @see ObjectStrategy#setReflective(boolean)
   * @see ObjectStrategy#setMaxRecursionDepth(int)
   */
  public executeInAreaOf__Object_obj__Runnable_logic__20__logic() {
    super();
    // uncomment to control the maximum reflective instantiation
    // recursion depth, 0 by default
    // setMaxRecursionDepth(0);
  }
}
