/*
 * Test data strategy for jml.javax.safetycritical.MemoryArea.
 *
 * Generated by JMLUnitNG 1.3 (103), 2013-06-16 04:48 +0200.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

package jml.javax.safetycritical.MemoryArea_JML_Data;


import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;
import jml.javax.safetycritical.PackageStrategy_java_lang_Class;
/**
 * Test data strategy for jml.javax.safetycritical.MemoryArea. Provides
 * class-scope test values for type java.lang.Class.
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2013-06-16 04:48 +0200
 */
public class ClassStrategy_java_lang_Class 
  extends PackageStrategy_java_lang_Class {
  /**
   * @return class-scope values for type java.lang.Class.
   */
  public RepeatedAccessIterator<?> classValues() {
    return new ObjectArrayIterator<Object>
    (new Object[] 
  	 { /* add class-scope java.lang.Class values or generators here */ });
  }

  /**
   * The use of reflection can be controlled here for  
   * parameters of type java.lang.Class
   * in this class by changing the parameters to <code>setReflective</code>
   * and <code>setMaxRecursionDepth<code>. 
   * In addition, the data generators used can be changed by adding 
   * additional data class lines, or by removing some of the automatically 
   * generated ones. Note that lower-level strategies can override any 
   * behavior specified here by calling the same control methods in 
   * their own constructors.
   *
   * @see NonPrimitiveStrategy#addDataClass(Class<?>)
   * @see NonPrimitiveStrategy#clearDataClasses()
   * @see ObjectStrategy#setReflective(boolean)
   * @see ObjectStrategy#setMaxRecursionDepth(int)
   */
  public ClassStrategy_java_lang_Class() {
    super();
    setReflective(false);
    // uncomment to control the maximum reflective instantiation
    // recursion depth, 0 by default
    // setMaxRecursionDepth(0);
  }
}
