/*
 * Test data strategy for jml.javax.safetycritical.MemoryArea.
 *
 * Generated by JMLUnitNG 1.3 (103), 2013-05-11 13:06 +0200.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

package jml.javax.safetycritical.MemoryArea_JML_Data;


import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;
import jml.javax.safetycritical.PackageStrategy_int;
/**
 * Test data strategy for jml.javax.safetycritical.MemoryArea. Provides
 * class-scope test values for type int.
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2013-05-11 13:06 +0200
 */
public class ClassStrategy_int 
  extends PackageStrategy_int {
  /**
   * @return class-scope values for type int.
   */
  public RepeatedAccessIterator<?> classValues() {
    return new ObjectArrayIterator<Object>
    (new Object[] 
  	 { /* add class-scope int values or generators here */ });
  }
  
  /**
   * defaultValues() from ClassStrategy_int; overridden by HSO
   * @return default values for type int.
   */
  public RepeatedAccessIterator<?> defaultValues() {
    return new ObjectArrayIterator<Object>
    (new Object[] 
     { /* add default int values or generators here */ 
        1, 100
     });
  }
}
