/*
 * Test data strategy for jml.javax.safetycritical.PriorityParameters.
 *
 * Generated by JMLUnitNG 1.3 (103), 2013-06-17 00:42 +0200.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

 
package jml.javax.safetycritical.PriorityParameters_JML_Data;

import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;

/**
 * Test data strategy for jml.javax.safetycritical.PriorityParameters. Provides
 * test values for parameter "int value" 
 * of method "void setPriority(int)". 
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2013-06-17 00:42 +0200
 */
public class setPriority__int_value__0__value
  extends ClassStrategy_int {
  /**
   * @return local-scope values for parameter 
   *  "int value".
   */
  public RepeatedAccessIterator<?> localValues() {
  	return new ObjectArrayIterator<Object>
  	(new Object[]
  	 { /* add local-scope int values or generators here */ 
  	    1, 50, 99, 100
  	 });
  }
}
